# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run tests and generate report
      run: |
        mkdir -p ./test/results
        cd ./test
        pytest test_buscaHorario.py --junitxml=results/results.xml 
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: dist/
    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: ./test/results/results.xml
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
    - name: Build package
      run: python setup.py sdist bdist_wheel
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: dist/

  notification:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
    - name: Enviando email
      uses: actions/checkout@v4
    - run: |
        chmod +x scripts/notification.sh
        sh scripts/notification.sh
    

    env:
      EMAIL_NOTIFICACAO: ${{ secrets.EMAIL_NOTIFICACAO }}

#uiuiuiuiuiuiuiui 